version: '3.4'

services:
  postgresdata:
    image: postgres
    container_name: dbserver
    environment:
      - POSTGRES_PASSWORD=Pa55word2019!123
    ports:
      - "54322:5432"
    volumes:
      - atocashdatavol:/var/opt/postgres/data
    networks:
      mynetwork:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=atominos@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Pa55word2019!123
    ports:
      - "5050:80"
    networks:
      mynetwork:
      
  atocash:
    image: ${DOCKER_REGISTRY-}ismi2u/atocashdev
    build:
      context: .
      dockerfile: AtoCash/Dockerfile
    command: tail -f /dev/null
    container_name: appserver
    tty: true
    ports:
      - "8080:80"
    networks:
      mynetwork:
    depends_on:
     - postgresdata

volumes:
    atocashdatavol:
    
networks:
    mynetwork:
        driver: bridge